### PR TITLE
Website mobile enhancement upgrade

### PR DESCRIPTION
**Pull request by cocoacacao**
for the love of good look this over and see if it'll break stuff

### CODE REVIEW

**Comment by vocatart** [comment]
please don't push to stale branches in the future.

**Comment by cocoacacao** [comment]
> please don't push to stale branches in the future.

LITERALLY WHAT DOES THIS MEAN

**Comment by vocatart** [comment]
> > please don't push to stale branches in the future.
> 
> LITERALLY WHAT DOES THIS MEAN

It's an unmaintained branch.

**Comment by cocoacacao** [comment]
> > > please don't push to stale branches in the future.
> > 
> > 
> > LITERALLY WHAT DOES THIS MEAN
> 
> It's an unmaintained branch.

STOP TYPING LIKE YOU'RE A PISSED OFF DISCORD MOD

**Comment by vocatart** [comment]
Closing this branch because its literally so broken please just make a new one

**Review by vocatart — COMMENTED** [review]
All changed denied. See pull request for more information.

**Pull request closed without merging**
